apiVersion: ai.sap.com/v1alpha1
kind: ServingTemplate
metadata:
  name: test-predictorv10
  annotations:
    scenarios.ai.sap.com/description: "just a test scenario"
    scenarios.ai.sap.com/name: "testing-cap"
    executables.ai.sap.com/description: "test-scenario-descr"
    executables.ai.sap.com/name: "test-scenario"
    executables.ai.sap.com/id: "test-scenario-serving-v1"
  labels:
    scenarios.ai.sap.com/id: "test-nagesh"
    ai.sap.com/version: 0.0.1
    ai.sap.com/resourcePlan: basic
spec:
  inputs:
    artifacts:
    - name: model_uri
  imagePullSecrets:
  - name: sfdnas-docker-secret
  template:
    spec: |
      predictor:
        minReplicas: 1
        maxReplicas: 2
        containers:
        - name: kserve-container
          image: "docker.io/sfdnasbhat/predictor:02"
          ports:
          - containerPort: 5000
            protocol: TCP
          env:
          - name: STORAGE_URI
            value: "{{inputs.artifacts.model_uri}}"
        imagePullSecrets:
        - name: sfdnas-docker-secret
    apiVersion: serving.kserve.io/v1beta1
