apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: predict-pipeline3 # executable id, must be unique across all your workflows (YAML files)
  annotations:
    scenarios.ai.sap.com/description: "description"
    scenarios.ai.sap.com/name: "name (Tutorial)" # Scenario name should be the use case
    executables.ai.sap.com/description: " live data"
    executables.ai.sap.com/name: "training" # Executable name should describe the workflow in the use case
    artifacts.ai.sap.com/housedataset.kind: "dataset" # Helps in suggesting the kind of inputs that can be attached.
  labels:
    scenarios.ai.sap.com/id: "learning-datalines"
    ai.sap.com/version: "1.0"
    ai.sap.com/resourcePlan: starter # computing power
spec:
  imagePullSecrets:
    - name: dckr_pat_iOZpHspmBcRxodGLlYf5__ogR6Y # your docker registry secret


  templates:
  - name: mypipeline
    steps:
    - - name: mypredictor
        template: mycodeblock1
  - name: mycodeblock1
    # Add your resource plan here. The annotation should follow metadata > labels > ai.sap.com/resourcePlan: <plan>
    inputs:
      artifacts:  # placeholder for cloud storage attachements
        - name: newdata # a name for the placeholder
          path: /app/data/ 
    template:
    
        metadata:        
        spec: |
          predictor:
            imagePullSecrets:
              - name: credstutorialrepo   # your docker registry secret
            minReplicas: 1
            containers:
            - name: kserve-container
              image: "docker.io/<YOUR_DOCKER_USERNAME>/house-server:01"
              ports:
                - containerPort: 9001    # customizable port
                  protocol: TCP
              command: ["/bin/sh", "-c"]
              args:
                - >
                  set -e && echo "Starting" && gunicorn --chdir python /app/src/main.py -b 0.0.0.0:9001 # filename `main` flask variable `app`
          env:
            - name: STORAGE_URI # Required
              value: "{{inputs.artifacts.housepricemodel}}" # Required reference from artifact name, see above
            - name: greetingmessage # different name to avoid confusion
              value: "{{inputs.parameters.greetmessage}}"
