apiVersion: ai.sap.com/v1alpha1
kind: ServingTemplate
metadata:
  name: serving
  annotations:
    scenarios.ai.sap.com/name: "name"
    executables.ai.sap.com/description: "des"
    executables.ai.sap.com/name: "test"
  labels:
    scenarios.ai.sap.com/id: "randomid"
    ai.sap.com/version: "0.1"
    ai.sap.com/resourcePlan: infer.s
    executables.ai.sap.com/id: "scenes-serving"
spec:
  inputs:
    parameters:
      - name: modelName
        default: "dummy"
        type: string
    artifacts:
      - name: modeluri
  imagePullSecrets:
    - name: dckr_pat_iOZpHspmBcRxodGLlYf5__ogR6Y
  template:
    spec: |
      default:
        predictor:
          minReplicas: 1
          custom:
            container:
              name: kfserving-container
              image: "docker.io/sfdnasbhat/hackathon-repo:latest"
              ports:
                - containerPort: 9001
                  protocol: TCP
              env:
                - name: STORAGE_URI
                  value: "{{inputs.artifacts.modeluri}}"
                - name: LOG_LEVEL
                  value: "0"
              command: ["/bin/sh", "-c"]
              args:
                - >
                  set -e && echo "starting " && gunicorn --chdir /src main:app -b 0.0.0.0:9001
