apiVersion: ai.sap.com/v1alpha1
kind: ServingTemplate
metadata:
  name: predictor-pipeline # executable ID, must be unique across your SAP AI Core instance, for example use `server-pipeline-yourname-1234`
  annotations:  
    scenarios.ai.sap.com/description: "record duplicate check"
    scenarios.ai.sap.com/name: "duplicate predict (Tutorial)"
    executables.ai.sap.com/description: "Create online server to make live duplicate check"
    executables.ai.sap.com/name: "server"
    artifacts.ai.sap.com/housepricemodel.kind: "model" # Suggest the kind of artifact to input.
  labels:
    scenarios.ai.sap.com/id: "predictor"
    ai.sap.com/version: "1.0"
    ai.sap.com/resourcePlan: starter # computing power
spec:
  inputs:
    artifacts:
      - name: newdata # placeholder name, do not add `-` in value use only alphanumeric chars
  template:
    spec: |
      predictor:
        imagePullSecrets:
          - name:    # your docker registry secret
        minReplicas: 1    # how much to scale
        containers:
        - name: kserve-container
          image: "docker.io/<YOUR_DOCKER_USERNAME>/house-server:01"
          ports:
            - containerPort: 9001    # customizable port
              protocol: TCP
          command: ["/bin/sh", "-c"]
          args:
            - >
              set -e && echo "Starting" && gunicorn --chdir /app/src main:app -b 0.0.0.0:9001 # filename `main` flask variable `app`
         
