--- 
apiVersion: ai.sap.com/v1alpha1
kind: ServingTemplate
metadata: 
  annotations: 
    artifacts.ai.sap.com/newdata.kind: dataset
    executables.ai.sap.com/description: "Create online server to make live duplicate check"
    executables.ai.sap.com/name: server
    scenarios.ai.sap.com/description: "duplicate return"
    scenarios.ai.sap.com/name: "record duplicate (Tutorial)"
  labels: 
    ai.sap.com/version: "1.0"
    scenarios.ai.sap.com/id: record-duplicate-check
  name: predictor-pipeline
      
spec:
  inputs:
    artifacts:
      - name: newdata #
        path: /app/data/ #placeholder name, do not add `-` in value use only alphanumeric chars
    parameters:
      - name: greetmessage # placeholder name
        type: string # required for every parameters
        
  template:
    apiVersion: "serving.kserve.org/v1beta1"

  imagePullSecrets:
    - name: dckr_pat_iOZpHspmBcRxodGLlYf5__ogR6Y # your docker registry secret
 
      
  container:
    - name: kserve-container
      image: "docker.io/sfdnasbhat/hackathon-repo:latest"
      ports:
          - containerPort: 9001    # customizable port
            protocol: TCP
      command: ["/bin/sh", "-c"]
      args:
        - >
          set -e && echo "Starting" && gunicorn --chdir /app/src main:app -b 0.0.0.0:9001 # filename `main` flask variable `app`
      env:
        - name: STORAGE_URI # Required
          value: "{{inputs.artifacts.newdata}}" # Required reference from artifact name, see above
        - name: greetingmessage # different name to avoid confusion
          value: "{{inputs.parameters.greetmessage}}"
      
