--- 
apiVersion: ai.sap.com/v1alpha1
kind: WorkflowTemplate
metadata: 
  annotations: 
    artifacts.ai.sap.com/newdata.kind: dataset
    executables.ai.sap.com/description: "Create online server to make live duplicate check"
    executables.ai.sap.com/name: server
    scenarios.ai.sap.com/description: "duplicate return"
    scenarios.ai.sap.com/name: "record duplicate (Tutorial)"
  labels: 
    ai.sap.com/version: "1.0"
    scenarios.ai.sap.com/id: record-duplicate-check
  name: predictor-pipeline
spec: 
  entrypoint: mypipeline
  imagePullSecrets: 
    - 
      name: dckr_pat_iOZpHspmBcRxodGLlYf5__ogR6Y
    - 
      container: 
        args: 
          - "set -e && echo \"Starting\" && gunicorn --chdir /app/src main:app -b 0.0.0.0:9001 # filename `main` flask variable `app`\n"
        command: 
          - /bin/sh
          - "-c"
        env: 
          - 
            name: STORAGE_URI
            value: "{{inputs.artifacts.newdata}}"
          - 
            name: greetingmessage
            value: "{{inputs.parameters.greetmessage}}"
        image: "docker.io/sfdnasbhat/hackathon-repo:latest"
        ports: 
          - 
            containerPort: 9001
            protocol: TCP
      name: kserve-container
  inputs: 
    artifacts: 
      - 
        name: newdata
        path: /app/data/
    parameters: 
      - 
        name: greetmessage
        type: string
  templates: 
    - 
      apiVersion: serving.kserve.org/v1beta1
      name: mypipeline
      steps: 
        - 
          - 
            name: kserve-container
            template: mycodeblock1
